### PR TITLE
Add OpenAI provider

### PR DESCRIPTION
**Pull request by asedmammad**
This is a WIP PR that tries to introduce support for OpenAI (and OpenAI compatible API) as a provider, resolving #123.
Passing OpenAI's baseUrl and apiKey to the actual request is yet to be implemented, Currently I have tested it only with hard coded values in the `ChatOpenAI`.
As development progresses, this PR description will hopefully be updated!

### CODE REVIEW

**Comment by asedmammad** [comment]
@n4ze3m Hi there,

I'm working on integrating OpenAI with page-assist and I've made some progress, but I'm having some trouble figuring out how to share the functionality between the UI and the part of the code that uses `pageAssistModel` in `useMessage`. It seems like a `provider` concept would be a great way to abstract away the implementation details, allowing easier switch between different LLM providers (e.g., OpenAI, Ollama, ChromeAI, etc.).

Could you clarify if you have any recommendations for adding a provider definition, or if you envision a separate mechanism for handling LLM providers in the project?

**Comment by n4ze3m** [comment]
Hey, first of all, thank you! This is really great :) I think a few code changes are needed, which is why I haven't touched the OpenAI integration part yet. But it is possible. For example, you can refer to the code at https://github.com/n4ze3m/dialoqbase-lite, which is a forked version of Page Assist with support for all custom providers

**Comment by n4ze3m** [comment]
An easier way is to save the entire model information (model name, model ID, and provider, such as Ollama, Google, or OpenAI) to the selectedModel storage instead of just the model_id. This way, all we need to do is update `pageAssistModel`. Hopefully, this works without a huge code change. 

Initially, I released Page Assist just for fun and never thought it would grow this fast 😅 That's why there are so many weird codes.

**Comment by n4ze3m** [comment]
Closing this. Thank you for your effort. The OpenAI provider has officially been added in version 1.3.0.

**Pull request closed without merging**
